services:
  nginx:
    image: nginx:1.19.2
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/configs:/etc/nginx/conf.d:ro
      - static:/data/static:ro
      - media:/data/media:ro
    networks:
      - movies-admin-app
      - movies-cluster
    depends_on:
      - auth_app_backend
      - app
      - admin_app_backend
    ports:
      - "80:80"

  admin_app_backend:
    build:
      context: app
    volumes:
      - static:/opt/app/static
      - media:/opt/app/media
    networks:
      - movies-admin-app
      - movies-cluster
    expose:
      - "8000"
    depends_on:
      admin_app_postgres:
        condition: service_healthy
    env_file: .env
    environment:
      ENVIRONMENT: LOCAL

  admin_app_postgres:
    image: postgres:15.5
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/create-content-schema.sh:/docker-entrypoint-initdb.d/create-content-schema.sh
      - ./postgres/backup.sql:/backup.sql
    networks:
      - movies-admin-app
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${DB_NAME} -U ${DB_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"

volumes:
  static:
  media:

networks:
  movies-admin-app:
    name: movies-admin-app
  movies-cluster:
    name: movies-cluster