version: '3'
services:
  service:
    build: app
    depends_on:
      - postgres
    expose:
      - "8000"
    environment:
      DB_PASSWORD: 123qwe
      DB_USER: app
      DB_NAME: movies_database

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./configs:/etc/nginx/conf.d:ro
      - ./data:/data/:ro
    depends_on:
      - service
    ports:
      - "80:80"

  postgres:
    image: postgres:13
    volumes:
      - ../../backup.sql:/docker-entrypoint-initdb.d/backup.sql
