# Generated by Django 4.2.6 on 2023-12-05 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_filmwork_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personfilmwork',
            name='role',
            field=models.CharField(choices=[('actor', 'actor'), ('director', 'director'), ('producer', 'producer'), ('writer', 'writer')], verbose_name='role'),
        ),
    ]
